package com.daogen.clotheme;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.daogen.clotheme.CategoryArchiveDao;
import com.daogen.clotheme.InitialFlagDao;
import com.daogen.clotheme.CategoryDao;
import com.daogen.clotheme.StyleDao;
import com.daogen.clotheme.ThicknessDao;
import com.daogen.clotheme.WearPlaceDao;
import com.daogen.clotheme.MeterialDao;
import com.daogen.clotheme.PersonInformationDao;
import com.daogen.clotheme.SeasonDao;
import com.daogen.clotheme.StorageLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CategoryArchiveDao.createTable(db, ifNotExists);
        InitialFlagDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        StyleDao.createTable(db, ifNotExists);
        ThicknessDao.createTable(db, ifNotExists);
        WearPlaceDao.createTable(db, ifNotExists);
        MeterialDao.createTable(db, ifNotExists);
        PersonInformationDao.createTable(db, ifNotExists);
        SeasonDao.createTable(db, ifNotExists);
        StorageLocationDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CategoryArchiveDao.dropTable(db, ifExists);
        InitialFlagDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        StyleDao.dropTable(db, ifExists);
        ThicknessDao.dropTable(db, ifExists);
        WearPlaceDao.dropTable(db, ifExists);
        MeterialDao.dropTable(db, ifExists);
        PersonInformationDao.dropTable(db, ifExists);
        SeasonDao.dropTable(db, ifExists);
        StorageLocationDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CategoryArchiveDao.class);
        registerDaoClass(InitialFlagDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(StyleDao.class);
        registerDaoClass(ThicknessDao.class);
        registerDaoClass(WearPlaceDao.class);
        registerDaoClass(MeterialDao.class);
        registerDaoClass(PersonInformationDao.class);
        registerDaoClass(SeasonDao.class);
        registerDaoClass(StorageLocationDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
