package com.daogen.clotheme;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.daogen.clotheme.CategoryArchive;
import com.daogen.clotheme.InitialFlag;
import com.daogen.clotheme.Category;
import com.daogen.clotheme.Style;
import com.daogen.clotheme.Thickness;
import com.daogen.clotheme.WearPlace;
import com.daogen.clotheme.Meterial;
import com.daogen.clotheme.PeopleInfo;
import com.daogen.clotheme.Season;
import com.daogen.clotheme.StorageLocation;

import com.daogen.clotheme.CategoryArchiveDao;
import com.daogen.clotheme.InitialFlagDao;
import com.daogen.clotheme.CategoryDao;
import com.daogen.clotheme.StyleDao;
import com.daogen.clotheme.ThicknessDao;
import com.daogen.clotheme.WearPlaceDao;
import com.daogen.clotheme.MeterialDao;
import com.daogen.clotheme.PeopleInfoDao;
import com.daogen.clotheme.SeasonDao;
import com.daogen.clotheme.StorageLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryArchiveDaoConfig;
    private final DaoConfig initialFlagDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig styleDaoConfig;
    private final DaoConfig thicknessDaoConfig;
    private final DaoConfig wearPlaceDaoConfig;
    private final DaoConfig meterialDaoConfig;
    private final DaoConfig peopleInfoDaoConfig;
    private final DaoConfig seasonDaoConfig;
    private final DaoConfig storageLocationDaoConfig;

    private final CategoryArchiveDao categoryArchiveDao;
    private final InitialFlagDao initialFlagDao;
    private final CategoryDao categoryDao;
    private final StyleDao styleDao;
    private final ThicknessDao thicknessDao;
    private final WearPlaceDao wearPlaceDao;
    private final MeterialDao meterialDao;
    private final PeopleInfoDao peopleInfoDao;
    private final SeasonDao seasonDao;
    private final StorageLocationDao storageLocationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryArchiveDaoConfig = daoConfigMap.get(CategoryArchiveDao.class).clone();
        categoryArchiveDaoConfig.initIdentityScope(type);

        initialFlagDaoConfig = daoConfigMap.get(InitialFlagDao.class).clone();
        initialFlagDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        styleDaoConfig = daoConfigMap.get(StyleDao.class).clone();
        styleDaoConfig.initIdentityScope(type);

        thicknessDaoConfig = daoConfigMap.get(ThicknessDao.class).clone();
        thicknessDaoConfig.initIdentityScope(type);

        wearPlaceDaoConfig = daoConfigMap.get(WearPlaceDao.class).clone();
        wearPlaceDaoConfig.initIdentityScope(type);

        meterialDaoConfig = daoConfigMap.get(MeterialDao.class).clone();
        meterialDaoConfig.initIdentityScope(type);

        peopleInfoDaoConfig = daoConfigMap.get(PeopleInfoDao.class).clone();
        peopleInfoDaoConfig.initIdentityScope(type);

        seasonDaoConfig = daoConfigMap.get(SeasonDao.class).clone();
        seasonDaoConfig.initIdentityScope(type);

        storageLocationDaoConfig = daoConfigMap.get(StorageLocationDao.class).clone();
        storageLocationDaoConfig.initIdentityScope(type);

        categoryArchiveDao = new CategoryArchiveDao(categoryArchiveDaoConfig, this);
        initialFlagDao = new InitialFlagDao(initialFlagDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        styleDao = new StyleDao(styleDaoConfig, this);
        thicknessDao = new ThicknessDao(thicknessDaoConfig, this);
        wearPlaceDao = new WearPlaceDao(wearPlaceDaoConfig, this);
        meterialDao = new MeterialDao(meterialDaoConfig, this);
        peopleInfoDao = new PeopleInfoDao(peopleInfoDaoConfig, this);
        seasonDao = new SeasonDao(seasonDaoConfig, this);
        storageLocationDao = new StorageLocationDao(storageLocationDaoConfig, this);

        registerDao(CategoryArchive.class, categoryArchiveDao);
        registerDao(InitialFlag.class, initialFlagDao);
        registerDao(Category.class, categoryDao);
        registerDao(Style.class, styleDao);
        registerDao(Thickness.class, thicknessDao);
        registerDao(WearPlace.class, wearPlaceDao);
        registerDao(Meterial.class, meterialDao);
        registerDao(PeopleInfo.class, peopleInfoDao);
        registerDao(Season.class, seasonDao);
        registerDao(StorageLocation.class, storageLocationDao);
    }
    
    public void clear() {
        categoryArchiveDaoConfig.getIdentityScope().clear();
        initialFlagDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        styleDaoConfig.getIdentityScope().clear();
        thicknessDaoConfig.getIdentityScope().clear();
        wearPlaceDaoConfig.getIdentityScope().clear();
        meterialDaoConfig.getIdentityScope().clear();
        peopleInfoDaoConfig.getIdentityScope().clear();
        seasonDaoConfig.getIdentityScope().clear();
        storageLocationDaoConfig.getIdentityScope().clear();
    }

    public CategoryArchiveDao getCategoryArchiveDao() {
        return categoryArchiveDao;
    }

    public InitialFlagDao getInitialFlagDao() {
        return initialFlagDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public StyleDao getStyleDao() {
        return styleDao;
    }

    public ThicknessDao getThicknessDao() {
        return thicknessDao;
    }

    public WearPlaceDao getWearPlaceDao() {
        return wearPlaceDao;
    }

    public MeterialDao getMeterialDao() {
        return meterialDao;
    }

    public PeopleInfoDao getPeopleInfoDao() {
        return peopleInfoDao;
    }

    public SeasonDao getSeasonDao() {
        return seasonDao;
    }

    public StorageLocationDao getStorageLocationDao() {
        return storageLocationDao;
    }

}
