package com.daogen.clotheme;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Meterial.
 */
public class Meterial {

    private long id;
    private String Description;
    private String PicPath;
    private String Memo;
    private Integer BelongCategoryID;
    private Integer LocationID;
    private Integer PersonID;
    private Integer SeasonID;
    private String LastWashDate;
    private Integer ThicknessID;
    private String UseDate;
    private String WearPlaceID;
    private Integer StyleID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Meterial() {
    }

    public Meterial(long id) {
        this.id = id;
    }

    public Meterial(long id, String Description, String PicPath, String Memo, Integer BelongCategoryID, Integer LocationID, Integer PersonID, Integer SeasonID, String LastWashDate, Integer ThicknessID, String UseDate, String WearPlaceID, Integer StyleID) {
        this.id = id;
        this.Description = Description;
        this.PicPath = PicPath;
        this.Memo = Memo;
        this.BelongCategoryID = BelongCategoryID;
        this.LocationID = LocationID;
        this.PersonID = PersonID;
        this.SeasonID = SeasonID;
        this.LastWashDate = LastWashDate;
        this.ThicknessID = ThicknessID;
        this.UseDate = UseDate;
        this.WearPlaceID = WearPlaceID;
        this.StyleID = StyleID;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getPicPath() {
        return PicPath;
    }

    public void setPicPath(String PicPath) {
        this.PicPath = PicPath;
    }

    public String getMemo() {
        return Memo;
    }

    public void setMemo(String Memo) {
        this.Memo = Memo;
    }

    public Integer getBelongCategoryID() {
        return BelongCategoryID;
    }

    public void setBelongCategoryID(Integer BelongCategoryID) {
        this.BelongCategoryID = BelongCategoryID;
    }

    public Integer getLocationID() {
        return LocationID;
    }

    public void setLocationID(Integer LocationID) {
        this.LocationID = LocationID;
    }

    public Integer getPersonID() {
        return PersonID;
    }

    public void setPersonID(Integer PersonID) {
        this.PersonID = PersonID;
    }

    public Integer getSeasonID() {
        return SeasonID;
    }

    public void setSeasonID(Integer SeasonID) {
        this.SeasonID = SeasonID;
    }

    public String getLastWashDate() {
        return LastWashDate;
    }

    public void setLastWashDate(String LastWashDate) {
        this.LastWashDate = LastWashDate;
    }

    public Integer getThicknessID() {
        return ThicknessID;
    }

    public void setThicknessID(Integer ThicknessID) {
        this.ThicknessID = ThicknessID;
    }

    public String getUseDate() {
        return UseDate;
    }

    public void setUseDate(String UseDate) {
        this.UseDate = UseDate;
    }

    public String getWearPlaceID() {
        return WearPlaceID;
    }

    public void setWearPlaceID(String WearPlaceID) {
        this.WearPlaceID = WearPlaceID;
    }

    public Integer getStyleID() {
        return StyleID;
    }

    public void setStyleID(Integer StyleID) {
        this.StyleID = StyleID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
