package com.daogen.clotheme;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PeapleInfo.
 */
public class PeapleInfo {

    private long id;
    private String PersonName;
    private Integer StyleID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PeapleInfo() {
    }

    public PeapleInfo(long id) {
        this.id = id;
    }

    public PeapleInfo(long id, String PersonName, Integer StyleID) {
        this.id = id;
        this.PersonName = PersonName;
        this.StyleID = StyleID;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getPersonName() {
        return PersonName;
    }

    public void setPersonName(String PersonName) {
        this.PersonName = PersonName;
    }

    public Integer getStyleID() {
        return StyleID;
    }

    public void setStyleID(Integer StyleID) {
        this.StyleID = StyleID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
