package com.daogen.clotheme;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Season.
 */
public class Season {

    private long id;
    private String Season;
    private Integer RecommendedThick;
    private String ProbablyTemp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Season() {
    }

    public Season(long id) {
        this.id = id;
    }

    public Season(long id, String Season, Integer RecommendedThick, String ProbablyTemp) {
        this.id = id;
        this.Season = Season;
        this.RecommendedThick = RecommendedThick;
        this.ProbablyTemp = ProbablyTemp;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getSeason() {
        return Season;
    }

    public void setSeason(String Season) {
        this.Season = Season;
    }

    public Integer getRecommendedThick() {
        return RecommendedThick;
    }

    public void setRecommendedThick(Integer RecommendedThick) {
        this.RecommendedThick = RecommendedThick;
    }

    public String getProbablyTemp() {
        return ProbablyTemp;
    }

    public void setProbablyTemp(String ProbablyTemp) {
        this.ProbablyTemp = ProbablyTemp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
