package com.daogen.clotheme;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table StorageLocation.
 */
public class StorageLocation {

    private long id;
    private String Location;
    private String LocationPath;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public StorageLocation() {
    }

    public StorageLocation(long id) {
        this.id = id;
    }

    public StorageLocation(long id, String Location, String LocationPath) {
        this.id = id;
        this.Location = Location;
        this.LocationPath = LocationPath;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public String getLocationPath() {
        return LocationPath;
    }

    public void setLocationPath(String LocationPath) {
        this.LocationPath = LocationPath;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
