package com.daogen.clotheme;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.daogen.clotheme.StorageLocation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table StorageLocation.
*/
public class StorageLocationDao extends AbstractDao<StorageLocation, Long> {

    public static final String TABLENAME = "StorageLocation";

    /**
     * Properties of entity StorageLocation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Location = new Property(1, String.class, "Location", false, "LOCATION");
        public final static Property LocationPath = new Property(2, String.class, "LocationPath", false, "LOCATION_PATH");
    };


    public StorageLocationDao(DaoConfig config) {
        super(config);
    }
    
    public StorageLocationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'StorageLocation' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "'LOCATION' TEXT," + // 1: Location
                "'LOCATION_PATH' TEXT);"); // 2: LocationPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'StorageLocation'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StorageLocation entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Location = entity.getLocation();
        if (Location != null) {
            stmt.bindString(2, Location);
        }
 
        String LocationPath = entity.getLocationPath();
        if (LocationPath != null) {
            stmt.bindString(3, LocationPath);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StorageLocation readEntity(Cursor cursor, int offset) {
        StorageLocation entity = new StorageLocation( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Location
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // LocationPath
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StorageLocation entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setLocation(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocationPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StorageLocation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StorageLocation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
