package com.daogen.clotheme;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table WearPlace.
 */
public class WearPlace {

    private long id;
    private String WearPlace;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WearPlace() {
    }

    public WearPlace(long id) {
        this.id = id;
    }

    public WearPlace(long id, String WearPlace) {
        this.id = id;
        this.WearPlace = WearPlace;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getWearPlace() {
        return WearPlace;
    }

    public void setWearPlace(String WearPlace) {
        this.WearPlace = WearPlace;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
